apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/davabdallah/argocd.git
    targetRevision: main #Use the appropriate branch name if not main 
    path: guestbook/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: guestbook-argocd
  syncPolicy:
    automated:
      prune: true
