apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davabdallah/argocd.git
    targetRevision: HEAD
    path: nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: web-app-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
